variable "aws_region" {}
variable "vpc_id" {}
variable "subnet_id" {}
variable "key_name" {}
variable "public_key_path" {}
variable "instance_count_t2" {}
variable "instance_count_m4" {}
variable "instance_type_t2" {}
variable "instance_type_m4" {}